veuillez télécharger le dataset qui est un fichier .csv disponible à l'adresse suivante :
<https://github.com/webdevproformation/m2-iot-juin2026/blob/main/jour03/08-titanic.csv>

In [ ]:
import pandas as pd

data = pd.read_csv("08-titanic.csv")
#      pd.read_json()
#      pd.read_excel()
#      pd.read_sql()

data.head(2) # afficher les premières lignes de ton fichier csv

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [12]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [ ]:
data.shape
# 1309 lignes => passagers
# 12 colonnes => caractéristiques 
#   - survived = 0 1
#   - sex  => homme femme
#   - age  => 
#   - Pclass => 1er classe 2eme classe et 3 eme classe

(1309, 12)

In [ ]:
data.describe() # donner des infos de bases sur tes données 
# la colonne age a des cellules vides 1046.000000

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,1309.000000,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000
mean,655.000000,0.377387,2.294882,29.881138,0.498854,0.385027,33.295479
std,378.020061,0.484918,0.837836,14.413493,1.041658,0.865560,51.758668
min,1.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,328.000000,0.000000,2.000000,21.000000,0.000000,0.000000,7.895800
50%,655.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,982.000000,1.000000,3.000000,39.000000,1.000000,0.000000,31.275000
max,1309.000000,1.000000,3.000000,80.000000,8.000000,9.000000,512.329200

nettoyage => supprimer les colonnes dont on n'a pas besoin ET enlever les lignes dans lesquelles il y a des cellules vides

supprimer des colonnes

In [20]:
data = pd.read_csv("08-titanic.csv")
data = data.drop(
        ['PassengerId', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
        axis=1)
data.head()

,Survived,Pclass,Name,Sex,Age
0,0,3,"Braund, Mr. Owen Harris",male,22.0
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0
2,1,3,"Heikkinen, Miss. Laina",female,26.0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0
4,0,3,"Allen, Mr. William Henry",male,35.0

supprimer toutes les lignes où l'âge est non noté

In [ ]:
data = data.dropna(axis=0)
data.describe()
data.shape

          Survived       Pclass          Age
count  1046.000000  1046.000000  1046.000000
mean      0.398662     2.207457    29.881138
std       0.489857     0.841497    14.413493
min       0.000000     1.000000     0.170000
25%       0.000000     1.000000    21.000000
50%       0.000000     2.000000    28.000000
75%       1.000000     3.000000    39.000000
max       1.000000     3.000000    80.000000